name : My First Workflow

on: [push]

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name : check repo
          uses: actions/checkout@v4

        - name: welcome
          run: echo "3aslema ye hmema"
        
        - name: list files
          run: ls
        
        - name: read files 
          run: cat README.md