name : My First Workflow

on: [push]

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name : check repo
          uses: actions/checkout@v4

        - name: list and read files
          run: |
           echo "3aslema ye hmema"
           ls -ltra
           cat README.md
        - name : generate ascii
          run : cowsay -f dragon "run " >> dragon.txt
            