name : generate ascii artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            
            - name: list files
              run: ls -ltra

            - name: execute script
              run: |
               chmod +x ascii-script.sh
               ./ascii-script.sh