name: "my second workflow"

on: 
  workflow_dispatch:

env:
  TEST_ENV_VAR: "zahr"
  ANOTHER_ENV_VAR: "hammami"

jobs:
  job1_build:
    runs-on: ubuntu-latest
    steps:
      - name: echo 1
        run: echo "$TEST_ENV_VAR, $ANOTHER_ENV_VAR"
      - name: echo 2
        run: echo "gatta3"
  job2_build:
    runs-on: ubuntu-latest
    steps:
      - name: echo 3
        run: |
          echo "wassup"
          sleep 600s