name: "my second workflow"

on:   
  workflow_dispatch:

env:
  TEST_ENV_VAR: "zahr"
  ANOTHER_ENV_VAR: "hammami"

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest, ubuntu-20.04]
        images: [hello-world, alpine]
        exclude:
          - images: alpine
            os: windows-latest
        include:
          - images: amd64/alpine
            os: ubuntu-20.04
    runs-on: ${{ matrix.os }}
    steps:
    - name: echo docker details
      run: docker info

    - name: run images on ${{ matrix.os }}
      run: docker run ${{ matrix.images }}