name : generate ascii artwork

on: push

jobs:
    job1_build:
        runs-on: ubuntu-latest
        steps:
            - name: install cowsay
              run: sudo apt-get install cowsay -y
            - name: execute cowsay cmd
              run: cowsay -f dragon "run for cover soy dragon" >> dragon.txt
            - name: upload file
              uses: actions/upload-artifact@v3
              with:
                name: dragon-text-file
                path: dragon.txt

    job2_test:
        runs-on: ubuntu-latest
        needs: job1_build
        steps:
            - name: download file
              uses: actions/download-artifact@v3
              with:
                name: dragon-text-file
                path: dragon.txt

            - name: test file exists
              run: grep -i "dragon" dragon.txt || echo "File not found"

    job3_deploy:
        runs-on: ubuntu-latest
        needs: job2_test
        steps:
            - name: download file
              uses: actions/download-artifact@v3
              with:
                name: dragon-text-file
                path: dragon.txt

            - name: display file content
              run: |
                cat dragon.txt
                ls -ltra