name: "my second workflow"

on: 
  workflow_dispatch:

env:
  TEST_ENV_VAR: "zahr"
  ANOTHER_ENV_VAR: "hammami"

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, unubntu-20.04]
        images: [hello-world, hello-world2]
    runs-on: ${{ matrix.os }}
    steps:
    - name: echo docker details
      run: docker info

    - name: run images on ${{ matrix.os }}
      run: docker run ${{ matrix.images }}