name: "filters workflow"

on:
    push:
        # branches-ignore:
        #     - feature/*
        #     - test/**
        branches:
            - main
            - '!feature/*'
    workflow_dispatch:
    pull_request:
        types:
            - opened
            - closed
        paths-ignore:
            - README.md
        branches:
            - main

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo this workflow/jobs/stepss is executed for event type - ${{ github.event_name }}
